### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#1]

**Comment by Sidahmeders** [comment]
@

**Comment by gffarah** [comment]
السلام عليكم من فضلك اريد المزيد من المعلومات الخاصه ب landing page

**Comment by Abdelaziz18003** [comment]
@gffarah هناك مصمم يعمل عليها حاليا ستكون جاهزة في غضون يوم أو يومين ان شاء الله

**Comment by gffarah** [comment]
ان شاء الله هل سيعمل ب html css js 
او على اطار خاص !

**Comment by Abdelaziz18003** [comment]
@gffarah 
نعم سيعمل بهذه التقنيات مع استعمال إطار العمل Bulma(css) عند الحاجة

**Comment by Sidahmeders** [comment]
when the UI design is ready let me handle it

**Comment by Abdelaziz18003** [comment]
@Sidahmeders I will assign this to you right now. I will notify you when the design is ready

**Comment by Abdelaziz18003** [comment]
@Sidahmeders here are the designs (implemented as static html using bootstrap) if you have time and you wanna help implementing them https://www.dropbox.com/s/civ2j09wuvl7pxf/Wakf.zip?dl=0
We need to implement the html page into our index page. Here are some guidelines:
- extract out header to `partials/header` so we can reuse it in all pages
- extract out footer to `partials/footer` so we can reuse it
- all css and js scripts links should be in the layout files
thanks :)

**Comment by Abdelaziz18003** [comment]
@Sidahmeders by the way no need to dowload the files, I already did that and include them in `public` folder with all the needed assets

**Comment by Sidahmeders** [comment]
should I use bootstrap, convert it to bulma OR only HTML/CSS

**Comment by Abdelaziz18003** [comment]
@Sidahmeders the pages are already styled using bootstrap, our mission will be to just integrate them in our views. We will be using the new designs instead of the basic ones that we already created. And we will switch from Bulma to Bootstrap since we found someone who is good with bootstrap and ready to help designing and coding all the pages.

**Comment by Sidahmeders** [comment]
> @Sidahmeders the pages are already styled using bootstrap, our mission will be to just integrate them in our views. We will be using the new designs instead of the basic ones that we already created. And we will switch from Bulma to Bootstrap since we found someone who is good with bootstrap and ready to help designing and coding all the pages.

pass my thanks to the guy who did all the design and implementation.
