### ISSUE TITLE
Create an admin dashboard page

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#3]

**Comment by ZakariaRebouhi** [comment]
please more details

**Comment by Sidahmeders** [comment]
assign this to me, I will make an initial setup and you guide me from there

**Comment by Abdelaziz18003** [comment]
@Sidahmeders thanks for your interest, but this task was assigned to Zakaria and he already completed it. We will need your help in other tasks :smile:
