### ISSUE TITLE
create a controller to handle user listing orders in /profile/orders

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#34]
**Some guidelines:**

- name the controller: get-user-orders.js
- use the same pattern as in /controllers/post-signup.js
- use-case to use: /use-cases/list-orders.js
- use fake ownerId for now (with a todo comment above it to get back to it later)

**Comment by Sidahmeders** [comment]
I will take this one

**Comment by Sidahmeders** [comment]
I Have faced a naming issue on the  /[waqf/use-cases/index.js](https://github.com/Waqf-DZ/waqf/blob/main/use-cases/index.js)

const makeGetAdminOrders = require('./list-orders')
const makeGetUserOrders = require('./list-orders')

const listOrders = makeGetUserOrders({ ordersDB: store })
const listOrders = makeGetAdminOrders({ ordersDB: store })

So.., should I rename the variables as **userListOrders** && **adminListOrders**
OR merge them in one variable as **listOrders** and rename the method instead as **makeGetOrders** and use it for both _(makeGetUserOrders, makeGetAdminOrders)_

**Comment by Abdelaziz18003** [comment]
@Sidahmeders there was some merge conflicts this morning when I was merging PRs, It is possible that I didn't pay attention to some piece of code that got merged without being properly resolved. But there should not be `makeGetAdminOrders` inside use cases, this is the name of the controller. The use-case needs to be named `makeListOrders` and it will be shared between `makeGetAdminOrders` and `makeGetUserOrders` controllers. But no worries, go ahead and implement the logic without worrying too much about the names. I will make a revision of the codebase this night Inchaa Allah and rename variables properly.

**Comment by Sidahmeders** [comment]
my bad, I didn't pay attention.
but I will be fixing variable names inside the [use-cases/index](https://github.com/Waqf-DZ/waqf/blob/main/use-cases/index.js) on this PR
