### ISSUE TITLE
Create an admin page where all users are listed

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#6]

**Comment by boudiishiba** [comment]
hello , assign this to me please

**Comment by Abdelaziz18003** [comment]
@boudiishiba the page is already there but empty `/infrastructure/web/views/admin/users/index.njk`
Here is the user creation form to see which fields are there and use it as a reference
![Screenshot 2021-07-30 at 13-46-08 منصة وقف لتسيير العتاد الوقفي](https://user-images.githubusercontent.com/11301627/127719445-f962b1c0-f209-491c-b53f-3acd920e9494.png)

**Comment by boudiishiba** [comment]
@Abdelaziz18003  please can you check if the  push commit is done i did it 2 days ago but i didnt found it now and i re-push it now so i dont know if the push commit is done !

**Comment by Abdelaziz18003** [comment]
completed
