### ISSUE TITLE
handle uploading prescription image when creating new order

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#64]
- we will use Multer package for that https://blog.logrocket.com/uploading-files-using-multer-and-node-js/
- images will be saved in /infrastructure/web/uploads folder (create a folder with this name with a .gitkeep file inside and commit it)
- the prescription image will be stored in /uploads and its path `/uploads/img.jpg` will be saved inside the order as `prescriptionUrl`

**Comment by Sidahmeders** [comment]
I will do it

**Comment by Abdelaziz18003** [comment]
@Sidahmeders Ok, thanks

**Comment by Sidahmeders** [comment]
my pleasure
