### ISSUE TITLE
allow users to view and edit product details

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#69]
See #68 for details

**Comment by Sidahmeders** [comment]
I will take this one

**Comment by Sidahmeders** [comment]
where is the assignment  😁 😁

**Comment by Abdelaziz18003** [comment]
@Sidahmeders haha I created those issues using my phone (and I am not good at using phone keyboard :smile: ) it is why I linked to the issue 68 above meaning that we want the same behaviour and follow  the same pattern for products too as we did for orders. let me know if this is not clear so I can provide more details :slightly_smiling_face:

**Comment by Sidahmeders** [comment]
I guess the details were clear, I only asked of you the green light  😇

**Comment by Abdelaziz18003** [comment]
@Sidahmeders :green_circle: :smile:
