### ISSUE TITLE
Create a user profile page where his own orders are listed

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#7]

**Comment by helliouss** [comment]
Hello, Assign this for me please

**Comment by islam36** [comment]
salam @Abdelaziz18003 , assign me to this task. Can you provide more details ? like what the structure of an order ? and since the backend is not implemented yet, do i just make static ones ?

**Comment by Abdelaziz18003** [comment]
@islam36 yes just make static ones for now. You can see the structure in issue #9 . Assigned to you.
