### ISSUE TITLE
Create a user profile page where his own products are listed

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#8]

**Comment by helliouss** [comment]
Hello, Assign this for me please

**Comment by seifooz** [comment]
I'm taking this task

**Comment by Abdelaziz18003** [comment]
@helliouss Ok, thanks.

**Comment by seifooz** [comment]
I'm a on the right direction ? 
<img width="795" alt="Capture d’écran 2021-07-31 à 16 56 04" src="https://user-images.githubusercontent.com/88212936/127743844-843fe17f-7a4a-4073-ae85-948b4547b823.png">

**Comment by Abdelaziz18003** [comment]
@helliouss yes looks good
