### ISSUE TITLE
implement the new order creation page design 

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#87]
The new design is in public folder

- make sure the input name attribute is correct
- don't include the header and footer in the njk template, just the main content (header and footer will be included globally in layouts)

**Comment by Sidahmeders** [comment]
I will take this one

**Comment by Sidahmeders** [comment]
in the DB there is **patientName** only but the design has a family && given name.
should I send both names and you combine them in the controller or should I remove the **familyName** field  from the form to match the previous form, and as of now I will be sending the  **countryState** and **countryDistrict**
