### ISSUE TITLE
Create a user profile page where he can create a new order

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#9]

**Comment by benomase2** [comment]
Hello, i want to work on this task

**Comment by seifooz** [comment]
Hello, Assign this to me

**Comment by Abdelaziz18003** [comment]
@helliouss, the order form has the following fields:

patientName إسم المريض
patientAge عمر المريض
oxygenRatio تركيز الأكسجين 
hasChronicDesease هل لدى المريض أمراض مزمنة؟
isCovid هل المريض مصاب بفيروس كورونا؟
prescription (file upload field) الوصفة الطبية

We already have a form in `/admin/users/new` that you may want to have a look on and use as a reference
thanks

**Comment by seifooz** [comment]
what about the prescription ? no need for a file input to upload it ?

**Comment by Abdelaziz18003** [comment]
@helliouss you are right, I dropped that by mistake. Thanks for pointing to that.
