### ISSUE TITLE
add new fields to Order

### ISSUE THREAD

**Issue by Abdelaziz18003** [Waqf-DZ/waqf#97]
fields to add:
- isHospitalized: true/false (هل المريض في المستشفى حاليا؟)
- wilaya: string,
- city: string,
- description: string (تفاصيل إضافية)

Those fields needs to be added to:
- makeOrder
- order form template
- order details page
- post new user order controller
- post new user
- update user order
- update admin order
- sequelize order model
- sequelize order repository
- make sure everything works well with the new fields (adding, updating, listing)

**Comment by Sidahmeders** [comment]
I will take this one

**Comment by Sidahmeders** [comment]
I guess isHospitalized shouldn't be added to post-new-user controller, so I won't be including it for now.

**Comment by Abdelaziz18003** [comment]
@Sidahmeders you are definitely right, I dropped it by mistake. Thanks for reporting that :+1:
